# Generated by Django 4.2 on 2025-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("category", models.TextField(db_index=True)),
                ("source", models.TextField()),
                ("author", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("url", models.TextField(unique=True)),
                ("url_to_image", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "news_articles",
            },
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["category", "published_at"],
                name="news_articl_categor_d829cb_idx",
            ),
        ),
    ]
